### ISSUE TITLE
出错

### ISSUE THREAD

**Issue by bbbbx** [Mooooooon/Musicoon#4]
用的第一版，
`Uncaught SyntaxError: Unexpected token < in JSON at position 0(…)   (index):1 `

**Comment by D-Bood** [comment]
感覚作者已经不维护了……

**Comment by farlandliu** [comment]
我的音乐APP：[Tencent App Store](http://android.myapp.com/myapp/detail.htm?apkName=io.dcloud.H57DA12F3)

**Comment by Mooooooon** [comment]
检查php版本
